spring:
  application:
    name: config-server
  cloud:
    config:
#      label: dev
      server:
        git:
          uri: https://github.com/mzl001/ugoodPro
          searchPaths: config-repo
          username: 1276581914@qq.com
          password: Mzl0923@ylm.com
server:
  port: 8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/