eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ugooddata?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0 #索引（默认为0）
    host: localhost #地址
    port: 6379 #端口号
    #password:  #连接密码（默认空）
    pool:
      max-idle: 8 #连接池中的最大空闲连接
      min-idle: 0 #连接池中的最小空闲连接
      max-active: 8 #连接池最大连接数（使用负值表示没有限制）
      max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制）
      #sentinel:
      #master: mymaster # 哨兵监听的Redis server的名称
      #nodes:
#127.0.0.1:26379,127.0.0.1:26479,127.0.0.1:26579 #哨兵的配置列表
      timeout: 5000 #连接超时时间（毫秒）
mybatis:
#  config-locations: classpath:mybatis-config.xml
  mapper-locations: classpath*:com/ugood/dao/*/*.xml
#  type-aliases-package: com.ugood.pojo
server:
  port: 8701
  context-path: /dome